name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Mend CLI
      run: |
        echo "Downlaoding the CLI"
        curl "https://downloads.mend.io/cli/linux_amd64/mend" -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        
    - name: Print Mend CLI Version
      run: |
        echo "Verifying the CLI version"
        mend version
        
    # - name: Resolve .NET dependencies
    #   run: nuget install
    # - name: Resolve Maven dependencies
    #   run: mvn clean install
    # - name: Resolve npm dependencies
    #   run: npm install
    # - name: Resolve pip dependencies
    #   run: pip install -r requirements.txt

    # - name: Run Mend CLI
    #   run: |
    #     mend dep --update --scope "Aayans Sandbox//SCA_CLI//${{ github.event.repository.name }}" --non-interactive
    #   env:
    #     MEND_USER_KEY: ${{ secrets.WS_USERKEY }}
    #     MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
    #     MEND_URL: ${{ secrets.MEND_URL }}
    #     MEND_LOG_LEVEL: "DEBUG"

    - name: Print dummy log file
      run: |
        mkdir -p "~/.mend/logs/sca" && touch "~/.mend/logs/sca/testsca.log"
        echo "Current Mend CLI version: $(mend version)" >> {HOME}/.mend/logs/sca/testsca.log
  
    - name: Find the newest Mend CLI SCA log file
      run: |
        ls -t ~/.mend/logs/
        ls -t ~/.mend/logs/sca/
        latest_file=$(ls -t ~/.mend/logs/sca/*.log | head -n 1)
        echo "LATEST_FILE=$latest_file" >> $GITHUB_ENV

    - name: Upload newest Mend CLI log as artifact
      uses: actions/upload-artifact@v4
      with:
        name: mend-cli-log
        path: ${{ env.LATEST_FILE }}
